/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for system monitoring. Used by load balancers and monitoring systems to verify system availability. Requires no authentication.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System is operational */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/api/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign up
         * @description Registers a user with email and password. The password is PBKDF2-hashed into `udb_user_password`, kept in a separate table from the `udb_user` profile, and the raw value is never stored.
         *     A session is issued as part of the same request, so the response already carries the `session` cookie and the caller is logged in — no follow-up login round trip.
         *     `email` is trimmed and lower-cased before the uniqueness check.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description Login ID. Already registered → 409.
                         * @example taro@example.com
                         */
                        email: string;
                        /**
                         * @description Raw password. Shorter than 8 characters → 400.
                         * @example password123
                         */
                        password: string;
                        /**
                         * @description Display name. Empty → 400.
                         * @example 山田 太郎
                         */
                        name: string;
                    };
                };
            };
            responses: {
                /** @description Registered, session cookie set */
                201: {
                    headers: {
                        /** @description Signed session cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: int64
                             * @description Management ID of the created user
                             * @example 1
                             */
                            id: number;
                        };
                    };
                };
                400: components["responses"]["400"];
                409: components["responses"]["409"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Looks the user up by email and compares the supplied password against the stored PBKDF2 hash. On success a fresh session row is inserted and the `session` cookie is set.
         *     An unknown email and a wrong password both return the same 401 with the same message, so the response cannot be used to probe which addresses are registered.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @example taro@example.com
                         */
                        email: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated, session cookie set */
                200: {
                    headers: {
                        /** @description Signed session cookie */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: int64
                             * @description Management ID of the authenticated user
                             * @example 1
                             */
                            id: number;
                        };
                    };
                };
                400: components["responses"]["400"];
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Deletes the `udb_user_session` row the cookie points at, then discards the cookie. Server side goes first, so the token is dead even for a client that keeps its copy.
         *     Idempotent: a request with no cookie, or one whose signature no longer verifies, still returns 204 rather than an error — there is nothing to reveal and nothing left to do.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out, session cookie discarded */
                204: {
                    headers: {
                        /** @description Discard instruction for the session cookie (Max-Age=0) */
                        "Set-Cookie"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                500: components["responses"]["500"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my profile
         * @description Resolves the logged-in user from the `session` cookie and returns the public profile. Authentication status is conveyed by the HTTP code (200 / 401), not a payload field.
         *     The cookie's HMAC signature is verified before any query runs, so a tampered cookie is rejected without touching the database. A token whose `udb_user_session` row is gone — logged out, or never issued — is a 401 even when the signature still checks out, because the row is the source of truth.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current authenticated user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: int64
                             * @description Management ID (internal sequence)
                             * @example 1
                             */
                            id: number;
                            /**
                             * Format: uuid
                             * @description Public identifier. Prefer this over `id` when exposing a user.
                             * @example 6486431a-3cac-4ba2-b32d-e67b673b8f76
                             */
                            uuid: string;
                            /**
                             * @description Display name
                             * @example 山田 太郎
                             */
                            name: string;
                            /**
                             * Format: email
                             * @description Login ID
                             * @example taro@example.com
                             */
                            email: string;
                        };
                    };
                };
                401: components["responses"]["401"];
                500: components["responses"]["500"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: {
        /** @description リクエスト不正。JSON のパース失敗（`Parsing Failure: ...`）、 デコード失敗（`Decoding Failure: ...`）、 バリデーション違反のいずれか。 */
        400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description 認証失敗。Cookie 未送信 (`The session token not found`)、 署名不正 (`Invalid token signature`)、 セッション失効 (`The session is no longer valid`)、 資格情報の不一致 (`invalid email or password`) のいずれか。 */
        401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description 競合。登録しようとした email が既に使われている。 */
        409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/plain": string;
            };
        };
        /** @description 想定外のサーバーエラー。mvc.ErrorHandler が整形して返す。 */
        500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example true */
                    error: boolean;
                    /** @example Unexpected error */
                    message: string;
                    /**
                     * @description HTTP ステータスコード
                     * @example 500
                     */
                    code: string;
                    /** @example [] */
                    errors?: string[];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
